export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PHY_DATA_START = 'PHY_DATA_START';
export const PHY_DATA_EDIT_SUCCESS = 'PHY_DATA_EDIT_SUCCESS';
export const PHY_DATA_SUCCESS = 'PHY_DATA_SUCCESS';
export const PHY_DATA_FAIL = 'PHY_DATA_FAIL';

export const FETCH_DEMOGRAPHIC_DATA = 'FETCH_DEMOGRAPHIC_DATA';
export const SAVE_DEMOGRAPHIC_DATA = 'SAVE_DEMOGRAPHIC_DATA';


//master allergies actiontypes

export const MASTER_START='MASTER_ALLERGIES_START';

export const MASTER_FAIL = 'MASTER_ALLERGIES_FAIL';

export const MASTER_POSTCALL_SUCCESS = 'MASTER_POSTCALL_SUCCESS';

export const MASTER_GETCALL_SUCCESS = 'MASTER_GETCALL_SUCCESS';

export const MASTER_PUTCALL_SUCCESS = 'MASTER_PUTCALL_SUCCESS';

export const MASTER_DELETECALL_SUCCESS  = 'MASTER_DELETECALL_SUCCESS';