export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const PHY_DATA_START = 'PHY_DATA_START';
export const PHY_DATA_EDIT_SUCCESS = 'PHY_DATA_EDIT_SUCCESS';
export const PHY_DATA_SUCCESS = 'PHY_DATA_SUCCESS';
export const PHY_DATA_FAIL = 'PHY_DATA_FAIL';

export const FETCH_DEMOGRAPHIC_DATA = 'FETCH_DEMOGRAPHIC_DATA';
export const SAVE_DEMOGRAPHIC_DATA = 'SAVE_DEMOGRAPHIC_DATA';